# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ staging-website ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:coverage
    - run: ./node_modules/.bin/codecov -t $CODECOV_TOKEN
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Dokku deploy
      uses: vitalyliber/dokku-github-action@v3.0
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        HOST: ${{ secrets.DOKKU_HOST_NAME }}
        PROJECT: ${{ secrets.DOKKU_APP_NAME }}
