# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ staging-website ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo show me that app name
    - run: echo this is the app name $DOKKU_APP_NAME
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:coverage && ./node_modules/.bin/codecov -t $CODECOV_TOKEN
      env:
        CI: true
        DOKKU_APP_NAME: ${{ secrets.DOKKU_APP_NAME }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
